#!/usr/bin/env python3

"""
Description: Clear shell history file.
Author: Alejandro Cervera
"""

import os
import sys
import argparse

argumentParser = argparse.ArgumentParser(
    usage="hc [OPTION]...",
    epilog="Author: Alejandro Cervera",
    description="Clear shell history file.")

scriptArguments = argumentParser.parse_args()

# pylint: disable=missing-function-docstring

def print_error(message):
    # https://stackoverflow.com/a/15808105
    print(message, file=sys.stderr)

historyFile = os.getenv("HISTFILE")

if historyFile is None:
    print_error("No history file to clear.")
    sys.exit(1)

elif not os.path.isfile(historyFile):
    print_error("History file must be a regular file.")
    sys.exit(1)

elif os.path.getsize(historyFile) == 0:
    print_error("Can not clear an empty history file.")
    sys.exit(1)

else:
    try:
        os.truncate(historyFile, 0)
        print("History file cleared successfully.")

    except PermissionError:
        print_error("History file must be writable so it can be cleared ")
        sys.exit(1)
