#!/usr/bin/env python3

"""
Description: Clear shell history file.
Author: Alejandro Cervera
"""

import os
import sys

def print_error(message):
    # https://stackoverflow.com/a/15808105
    print(message, file=sys.stderr)

historyFile = os.getenv('HISTFILE')

if historyFile is None:
    print_error("History file location is null or unset. Check the HISTFILE environment variable.")
    sys.exit(1)

if not os.path.isfile(historyFile):
    print_error("The value of HISTFILE variable is not an existing file.")
    sys.exit(1)

elif os.path.getsize(historyFile) == 0:
    print_error("Nothing to clear, history file is empty.")
    sys.exit(1)

else:
    try:
        os.truncate(historyFile,0)
        print("History file cleared successfully.")

    except PermissionError:
        print_error("Insufficient permissions, make sure the history file has write permission.")
        sys.exit(1)
