#!/usr/bin/env python3

import sys
import os
import re
import argparse

# Properties for text output.
LIGHT_RED, RESET = "\033[0m", "\033[91m"

argumentParser = argparse.ArgumentParser(
    usage="ilo [OPTION]...",
    epilog="Author: Alejandro Cervera",
    description="Show information of a Linux system.")

scriptArguments = argumentParser.parse_args()

if sys.platform != "linux":
    print(f"{LIGHT_RED}ERROR:{RESET} Information will only be shown for Linux systems.")
    sys.exit(1)

# Show a simple message.
with open("/proc/sys/kernel/hostname") as hostnameFile:
    systemHostname = re.sub("\n", "", hostnameFile.read())

print(f"Information for system: {os.getenv('USER')}@{systemHostname}\n")

# Distribution.

# pylint: disable=pointless-string-statement

"""
Get a dictionary with keys and values set in os-release file.

Reference: https://stackoverflow.com/a/30020739
"""

keyValuePairs = {}

with open("/etc/os-release") as fileLines:
    for keyValuePair in fileLines:
        # Separate variable assignments into keys and values.
        key, value = keyValuePair.split("=")
        keyValuePairs[key] = value

# Parse distribution name.
distributionName = re.sub("\"|\n", "", keyValuePairs["NAME"])

print(f"Distribution: {distributionName}")

# Shell

systemShell = os.path.basename(os.getenv("SHELL"))

if systemShell is None:
    print(f"Shell: {LIGHT_RED}Could not be detected.{RESET}")
else:
    print(f"Shell: {systemShell}")

# Kernel version.
with open("/proc/sys/kernel/osrelease") as kernelVersion:
    print(f"Kernel version: {kernelVersion.read()}")

# CPU model names
print("CPU(s):\n")

with open("/proc/cpuinfo") as cpuInformationFile:
    for fileLine in cpuInformationFile:
        if re.match("^(model name)", fileLine):
            lineFields = fileLine.split(":")
            print(re.sub("\n", "", lineFields[1]).strip())
        else:
            continue

# pylint: disable=pointless-string-statement

"""
Uptime

Inspired by: https://github.com/dylanaraps/neofetch/blob/master/neofetch
"""

# pylint: disable=anomalous-backslash-in-string

with open("/proc/uptime") as uptimeFile:
    fileFields = uptimeFile.read().split()
    # Remove decimal numbers.
    systemUptime = int(re.sub("\.\d+", "", fileFields[0]))

print(f"\nUptime: \
{systemUptime // 60 // 60 // 24 % 24} day(s)    \
{systemUptime // 60 // 60 % 3600} hour(s)   \
{systemUptime // 60 % 60} minute(s)")

# Memory
print("\nTotal RAM and Swap:\n")

with open("/proc/meminfo") as memoryInformationFile:
    for fileLine in memoryInformationFile:
        if re.match("(Mem|Swap)Total", fileLine):
            lineFields = fileLine.split(":")
            # Parse memory
            totalMemory = int(re.sub("[A-Za-z]+|\n", "", lineFields[1]).strip())
            # Convert to gigabytes
            print(f"{totalMemory // 1048576} GB")
