#!/usr/bin/env python3

import sys
import os
import re
import argparse

# Colors for output.
LIGHT_YELLOW = "\033[93m"
LIGHT_GREEN = "\033[92m"
LIGHT_RED = "\033[91m"
RESET = "\033[0m"

argumentParser = argparse.ArgumentParser(
    usage="ilo [OPTION]...",
    epilog="Author: Alejandro Cervera",
    description="Show system information with some eye candy.")

scriptArguments = argumentParser.parse_args()

if sys.platform != "linux":
    print(f"{LIGHT_RED}ERROR:{RESET} Information will only be shown for Linux systems.")
    sys.exit(1)

with open("/proc/sys/kernel/hostname") as hostnameFile:
    systemHostname = re.sub("\n", "", hostnameFile.read())

# Print a nice banner.

# Dynamically create part of the banner.
remainingBanner = "-" * len(f"{os.getenv('USER')}@{systemHostname}")

print(f"""
{LIGHT_YELLOW}------------------------{remainingBanner}{RESET}
System information for: {os.getenv('USER')}@{systemHostname}
{LIGHT_YELLOW}------------------------{remainingBanner}{RESET}
""")

# Show system information.

"""
Get a dictionary with keys and values set in os-release file.

Reference: https://stackoverflow.com/a/30020739
"""

keyValuePairs = {}

with open("/etc/os-release") as fileLines:
    for keyValuePair in fileLines:
        # Separate variable assignments into keys and values.
        key, value = keyValuePair.split("=")
        keyValuePairs[key] = value

# Parse distribution name.
distributionName = re.sub('"|\n', "", keyValuePairs['NAME'])

print(f"Distribution: {distributionName}")

# Shell and version.

# Reference: https://linuxhandbook.com/execute-shell-command-python

systemShell = os.path.basename(os.getenv("SHELL"))

match systemShell:
    case "bash":
        firstLine = os.popen(f"{systemShell} --version").readline()

        lineFields = firstLine.split()

        shellVersion = lineFields[3]

        print(f"Shell: {systemShell} {shellVersion}")

    case "zsh":
        lineFields = os.popen(f"{systemShell} --version").read().split()

        shellVersion = lineFields[1]

        print(f"Shell: {systemShell} {shellVersion}")

    case _:
        print(f"Shell: {LIGHT_RED}Could not be detected.{RESET}")

# Kernel version.
with open("/proc/sys/kernel/osrelease") as kernelVersion:
    print(f"Kernel version: {kernelVersion.read()}")

# CPU model names
print("CPU(s):\n")

with open("/proc/cpuinfo") as cpuInformationFile:
    for fileLine in cpuInformationFile:
        if re.match("^(model name)", fileLine):
            lineFields = fileLine.split(":")
            # Remove trailing newline and spaces from model name.
            print(re.sub("\n", "", lineFields[1]).strip())
        else:
            continue

# Uptime

# Inspired by: https://github.com/dylanaraps/neofetch/blob/master/neofetch
with open("/proc/uptime") as uptimeFile:
    fileFields = uptimeFile.read().split()
    # Remove decimal numbers.
    systemUptime = int(re.sub("\.\d+", "", fileFields[0]))

uptimeMinutes, uptimeHours, uptimeDays = systemUptime // 60 % 60, systemUptime // 60 // 60 % 3600, systemUptime // 60 // 60 // 24 % 24

print(f"\nUptime: {uptimeDays} day(s)    {uptimeHours} hour(s)    {uptimeMinutes} minute(s)")

# Memory
print("\nTotal RAM and Swap:\n")

with open("/proc/meminfo") as memoryInformationFile:
    for fileLine in memoryInformationFile:
        if re.match("(Mem|Swap)Total", fileLine):
            lineFields = fileLine.split(":")
            # Parse memory
            totalMemory = int(re.sub("[A-Za-z]+|\n", "", lineFields[1]).strip())
            # Convert to gigabytes
            print(f'{totalMemory // 1048576} GB')
